#For the provider URL: Use https://token.actions.githubusercontent.com
#For the "Audience": Use sts.amazonaws.com
name: AWS OIDC Connect Demo
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.github/*'
env:
  AWS_REGION : "us-east-2"
  BUCKET_NAME: "abhibongale-serverless-chat-app"
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  AuthWithOIDC:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubOICDAuthenticationForChatAppRole
          role-session-name: GithubOICDAuthenticationForChatAppRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Fetch caller Identity
        run: |
          aws sts get-caller-identity
      # upload all the files to AWS s3
      - name: Copy Website to s3
        run: |
          aws s3 cp . s3://${{ env.BUCKET_NAME }} --recursive